services:
  # Backend Service
  - type: web
    name: role-based-security-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: MONGO_URI
        sync: false   # You’ll add your MongoDB URI in Render dashboard
      - key: JWT_SECRET
        sync: false   # Add your JWT secret in Render dashboard

  # Frontend Service
  - type: web
    name: role-based-security-frontend
    env: static
    rootDir: client
    buildCommand: "npm install && npm run build"
    staticPublishPath: "build"
    envVars:
      - key: REACT_APP_API_URL
        sync: false   # Add your backend URL after deploying backend
